### ISSUE TITLE
[Suggestion] Radius

### ISSUE THREAD

**Issue by ghost** [PokeGoRadar/pokegoradar#3]
Much needed control over the size of the area to scan. Multi account support is wasted by the tiny area it actually scans.

**Comment by Delloman** [comment]
Plz we need this

**Comment by imadeyoureadpoop** [comment]
Radius adjustment might be difficult, Niantic have changed the search radius. What would be interesting is a search shape option, as in whether to search in a box, a circle, or a straight line. For example, the straight line search would give me the ability to see a few hundred metres ahead of me on a bikepath (which would be very useful), whereas the square more useful in wide open spaces, and a circle of overlapping steps better in high density areas where exact placement is more favourable.

**Comment by voidpublic** [comment]
I suggest using a certain shape, like this:

http://i.imgur.com/dY5cxhy.png

But with multiple accounts:
This covers quite a lot of area in a relatively short time (with 5 sec delay and 4 accounts this should be easily covering everything within walking distance)

**Comment by PokeGoRadar** [comment]
This is indeed MUCh needed. We will rework the way we calculate the the scanning point!

**Comment by ghost** [comment]
@imadeyoureadpoop I mean, a scanning method like those used by Pokescanner and Pokemap, they can use different amounts of "steps".

**Comment by ghost** [comment]
@PokGoRadar I meant to extend the area searched such as with other apps have called "steps", not the actual radius of the map, you should find an appropriate title to change this to, I actually can't because I'm on mobile at the moment.

**Comment by PokeGoRadar** [comment]
@Lionir Are you referring as what @voidpublic posted as screenshot? 
I can see these circle/square being manually put by the user wherever he wants on the map

**Comment by ghost** [comment]
@PokeGoRadar Yes, I'm referring to such process, manually putting these would be extremely long and the areas scanned are not shown in this version and many apps does such process by default. You could go and see what they've done to make it happen and try to implement multiple account processing to increase the speed tremendously.

**Comment by PokeGoRadar** [comment]
This seems a good start, all of us are at work at the moment, we will start looking into it this afternoon. Expect to see an quick update tonight

**Comment by voidpublic** [comment]
@PokeGoRadar actually the circles are automatically placed, based on the position of the player.

So the position of the player is creating the first circle and the other ones build up to that. With that you have the maximum efficiency doing the scans. With multiple accounts (say 5) where each one makes 1 circle every 5 seconds you would scan an area of about 500m in less than 1min, which would be pretty neat

**Comment by PokeGoRadar** [comment]
In the current code in master the app creates 25 (it is fixed for now) of these circles
. . . . .
. . . . .
. . . . .
. . . . .
. . . . .

It makes up an area off approximatively 600m square. With 4 account currently on my phone it takes up 30 seconds

In case you have 4 accounts, the jobs are divided like these

acc1 acc2 acc3 acc4
acc1 acc2 acc3 acc4
acc1 acc2 acc3 acc4
acc1 acc2 acc3 acc4
acc1 acc2 acc3 acc4

the first line is run concurrently
wait 5 seconds
the second line is run concurrently
wait 5 seconds
etc..

In case you have 10 accounts, the jobs are divided like these

acc1 acc2 acc3 acc4
acc5 acc6 acc7 acc8
acc9 acc10 acc1 acc2
acc3 acc4 acc5 acc6
acc7 acc7 acc9 acc19

1) acc1 acc2 acc3 acc4 are run concurrently as soon as one these finished acc5 starts etc..

For the moment it still quite 'sequential' 

Instead we are thinking of having an "account pool" with the rule that an account is in the pool and ready to use once it has waited 6 seconds.

**Comment by voidpublic** [comment]
So how are the circles created? 
do you actually shape a hexagon or still a rectangle?

**Comment by PokeGoRadar** [comment]
The shape doesn't really matter to be honest. This is just a UI thing,
http://imgur.com/a/m7GXl
Instead of circles I display a black rectangle. Just imagine there is 25 circle inside that rectangle

What matters are the placement of the scanning point. the more scanning point you have the bigger the scan zone, the more account you can use the more thread you can use

**Comment by PokeGoRadar** [comment]
@voidpublic @Lionir 
http://imgur.com/a/qlkQw

Scanned in 2min with 6 accounts
