### ISSUE TITLE
Suggestion: Have the app run in background and give notifications for tracked pokemons

### ISSUE THREAD

**Issue by voidpublic** [PokeGoRadar/pokegoradar#5]
So it would be really neat to have the app running the scans every minute or so and give a notification when one of the tracked pokemon appears

**Comment by PokeGoRadar** [comment]
This feature is actually done developing. 
http://imgur.com/a/mWuvT
(When you tap the notification it will bring you to the map)

We are testing it today

**Comment by voidpublic** [comment]
Nice, can be closed then :)
